config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/top'
  root to: 'homes#top'
  
  resources :books
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
       redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
       render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
       render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<html>
 <body>

  <h1>Editing Book</h1>
  
  <%= form_with model:@book, local:true do |f| %>
   <h6>Title</h6>
    <div><%= f.text_field :title %></div>
   <h6>Body</h6>
    <div><%= f.text_area :body %></div>
   <div><%= f.submit "Update Book" %></div>
  <% end %>
  
  <%= form_for @book do |f| %>
   <% if @book.errors.any? %>
    <h2>error</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
    </ul>
   <% end %>
  <% end %>

  <div class = inlineblock>
   <div class = Show-Edit>
    <%= link_to "Show", book_path %>
   </div>
   <div class = Show-Back>
   <%= link_to "Back", books_path %>
   </div>
  <div>

 </body>
</html>

app/views/books/index.html.erb
 <html>
   <body>

     <p><%= flash[:notice] %></p>

     <h1>Books</h1>

     <table>
       <thead>
         <tr>
           <th>Title</th>
           <th>Body</th>
           <th colspan　= "3"></th>
         </tr>
       </thead>

       <tbody>
        <% @books.each do |list| %>
         <tr>
          <td><%= list.title %></td>
          <td><%= list.body %></td>
          <td><%= link_to "Show", book_path(list.id) %></td>
          <td><%= link_to "Edit", edit_book_path(list.id) %></td>
          <td><%= link_to "Destroy", "/books/#{list.id}", method: :delete %></td>
         </tr>
        <% end %>
       </tbody>
     </table>

     <%= form_with model:@book, local:true do |f| %>
      <h2>New book</h2>
      <h6>Title</h6>
       <div><%= f.text_field :title %></div>
      <h6>Body</h6>
       <div><%= f.text_area :body %></div>
      <div><%= f.submit "Create Book" %></div>
     <% end %>
     
     <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
       <h2>error</h2>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>
     <% end %>

   </body>
 </html>

app/views/books/show.html.erb
<html>
  <body>
    
    <p><%= flash[:notice] %></p>

    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>
    <p>
      <strong>Body:</strong>
      <%= @book.body %>
    </p>
    
    <div class = inlineblock>
      <div class = Show-Edit>
        <%= link_to "Edit", edit_book_path %>
      </div>
      <div class = Show-Back>
        <%= link_to "Back", books_path %>
      </div>
    <div>
      
  </body>
</html>

app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/books/top.html.erb</p>

app/views/homes/top.html.erb
<html>
  <body>
    <h1>
      ようこそ<strong>Bookers</strong>へ！
    </h1>
    <p>
      <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <p>
      <%= link_to "start", books_path %>
    </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>